name: user_db_drift
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^12.1.3
  hive_generator: ^2.0.1
  path_provider: ^2.1.1
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  faker: ^2.1.0
  reactive_forms: ^16.1.1
  intl: ^0.19.0
  path: ^1.8.3
  sqlite3: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  drift_dev: ^2.14.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg